name = "NLPModelsJuMP"
uuid = "792afdf1-32c1-5681-94e0-d7bf7a5df49e"
version = "0.13.5"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
JuMP = "1.25"
LinearAlgebra = "1.10"
MathOptInterface = "1.46"
NLPModels = "0.21.6"
NLPModelsTest = "0.10.6"
Percival = "0.7.3"
Printf = "1.10"
SolverCore = "0.3.9"
SparseArrays = "1.10"
Test = "1.10"
julia = "1.10"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLPModelsTest = "7998695d-6960-4d3a-85c4-e1bceb8cd856"
Percival = "01435c0c-c90d-11e9-3788-63660f8fbccc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "NLPModelsTest", "Percival", "Test"]
